"""
ZTP Server — FastAPI.

Endpoints:
  GET  /ztp.py          → отдаёт ZTP скрипт коммутатору
  GET  /config/{serial} → генерирует EOS конфиг из NetBox по серийнику
  GET  /ztp-done/{serial} → помечает устройство в NetBox как задеплоенное

Запуск:
  pip install -r requirements.txt
  cp .env.example .env  # заполни NETBOX_URL, NETBOX_TOKEN
  uvicorn app:app --host 0.0.0.0 --port 80
"""

import os
import pynetbox
from fastapi import FastAPI, HTTPException
from fastapi.responses import PlainTextResponse
from dotenv import load_dotenv

load_dotenv()

app = FastAPI(title="ZTP Server")

NETBOX_URL      = os.environ["NETBOX_URL"]
NETBOX_TOKEN    = os.environ["NETBOX_TOKEN"]
ADMIN_PASSWORD  = os.environ.get("ADMIN_PASSWORD", "123456")

ZTP_SCRIPT_PATH = os.path.join(os.path.dirname(__file__), "ztp_script.py")


def get_nb():
    return pynetbox.api(NETBOX_URL, token=NETBOX_TOKEN)


# ─── Endpoints ────────────────────────────────────────────────────────────────

@app.get("/ztp.py", response_class=PlainTextResponse)
def serve_ztp_script():
    """Арista скачивает этот скрипт и выполняет его при ZTP."""
    with open(ZTP_SCRIPT_PATH) as f:
        return f.read()


@app.get("/config/{serial}", response_class=PlainTextResponse)
def get_config(serial: str):
    """
    Возвращает EOS startup-config для устройства с указанным серийником.
    Коммутатор сохраняет его как startup-config и перезагружается.
    """
    nb = get_nb()

    # Ищем устройство по серийному номеру
    device = nb.dcim.devices.get(serial=serial)
    if not device:
        raise HTTPException(
            status_code=404,
            detail=f"Устройство с serial={serial} не найдено в NetBox",
        )

    config = build_eos_startup_config(nb, device)
    return config


@app.get("/ztp-done/{serial}")
def ztp_done(serial: str):
    """
    Вызывается коммутатором после успешного применения конфига.
    Снимаем тег config-pending, ставим статус active.
    """
    nb = get_nb()

    device = nb.dcim.devices.get(serial=serial)
    if not device:
        raise HTTPException(status_code=404, detail=f"serial={serial} не найден")

    # Снимаем тег config-pending
    tags = [t for t in (device.tags or []) if t.slug != "config-pending"]

    # Добавляем тег config-deployed
    deployed_tag = _get_or_create_tag(nb, "config-deployed", "config-deployed", "4caf50")
    tags.append(deployed_tag)

    device.update({"tags": [{"id": t.id} for t in tags], "status": "active"})

    return {"status": "ok", "device": device.name}


# ─── Config builder ───────────────────────────────────────────────────────────

def build_eos_startup_config(nb, device) -> str:
    """
    Генерирует полный EOS startup-config из данных NetBox.
    Возвращает текст конфига (не список команд).
    """
    lines = []
    lines.append("! Generated by ZTP Server from NetBox")
    lines.append(f"! Device: {device.name}  Serial: {device.serial}")
    lines.append("!")

    # Hostname
    lines.append(f"hostname {device.name}")
    lines.append("!")

    # Admin user + SSH
    lines.append(f"username admin privilege 15 role network-admin secret 0 {ADMIN_PASSWORD}")
    lines.append("!")
    lines.append("aaa authentication login default local")
    lines.append("!")
    lines.append("management ssh")
    lines.append("   no shutdown")
    lines.append("!")
    lines.append("management api http-commands")
    lines.append("   protocol http")
    lines.append("   no shutdown")
    lines.append("!")

    # Management interface из primary_ip4
    if device.primary_ip4:
        import ipaddress
        primary = str(device.primary_ip4)          # например 10.0.1.10/24
        net = ipaddress.ip_interface(primary).network
        gateway = str(next(net.hosts()))            # первый IP префикса = .1

        # Определяем имя интерфейса из NetBox (assigned_object)
        ip_obj = nb.ipam.ip_addresses.get(device.primary_ip4.id)
        if ip_obj and ip_obj.assigned_object:
            mgmt_iface = ip_obj.assigned_object.name
        else:
            mgmt_iface = "Management0"

        lines.append(f"interface {mgmt_iface}")
        lines.append(f"   ip address {primary}")
        lines.append("   no shutdown")
        lines.append("!")
        lines.append(f"ip route 0.0.0.0/0 {gateway}")
        lines.append("!")

    # Получаем интерфейсы
    interfaces = list(nb.dcim.interfaces.filter(device_id=device.id))

    # Собираем нужные VID только с интерфейсов у которых задан mode
    needed_vids = set()
    for iface in interfaces:
        if not iface.mode:
            continue
        if iface.untagged_vlan:
            needed_vids.add(iface.untagged_vlan.vid)
        if iface.tagged_vlans:
            for v in iface.tagged_vlans:
                needed_vids.add(v.vid)

    # VLAN база — запрашиваем каждый VID отдельно (pynetbox REST API)
    if needed_vids:
        lines.append("! === VLANs ===")
        seen_vids = {}
        for vid in sorted(needed_vids):
            vlans = nb.ipam.vlans.filter(vid=vid)
            for vlan in vlans:
                if vlan.vid not in seen_vids:
                    seen_vids[vlan.vid] = vlan.name
                    break  # берём первый совпавший, остальные дубликаты пропускаем
        for vid in sorted(seen_vids):
            lines.append(f"vlan {vid}")
            lines.append(f"   name {seen_vids[vid]}")
        lines.append("!")

    # Интерфейсы
    lines.append("! === Interfaces ===")
    for iface in sorted(interfaces, key=lambda i: i.name):
        if not iface.mode:
            continue

        lines.append(f"interface {iface.name}")

        if iface.description:
            lines.append(f"   description {iface.description}")

        mode = iface.mode.value if hasattr(iface.mode, "value") else str(iface.mode)

        if mode == "access":
            lines.append("   switchport mode access")
            if iface.untagged_vlan:
                lines.append(f"   switchport access vlan {iface.untagged_vlan.vid}")

        elif mode == "tagged":
            lines.append("   switchport mode trunk")
            if iface.tagged_vlans:
                unique_vids = sorted(set(v.vid for v in iface.tagged_vlans))
                vids = ",".join(str(v) for v in unique_vids)
                lines.append(f"   switchport trunk allowed vlan {vids}")

        elif mode == "tagged-all":
            lines.append("   switchport mode trunk")

        if iface.mtu:
            lines.append(f"   mtu {iface.mtu}")

        lines.append("   no shutdown" if iface.enabled else "   shutdown")
        lines.append("!")

    lines.append("end")
    return "\n".join(lines)


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _get_or_create_tag(nb, slug: str, name: str, color: str = "00bcd4"):
    tag = nb.extras.tags.get(slug=slug)
    if not tag:
        tag = nb.extras.tags.create({"name": name, "slug": slug, "color": color})
    return tag
